Improve Lua support
unikraft/app-lua pull request #10
Opened 2023-07-26 22:14 UTC by razvand

Add template configuration files and draft instructions for Lua support in Unikraft.

2023-07-29 20:49 UTC, RaduNichita requested changes
Thanks, @razvand. 

I left some comments, I will test tommorow the application.

2023-07-29 20:49 UTC, RaduNichita commented on README.md
> +```console
```suggestion
## Configure 

```console
```

2023-07-29 20:49 UTC, RaduNichita commented on README.md
> +```console
I think it's better to have some scripts to run the app, similar to [here](https://github.com/unikraft/app-redis)

2023-07-29 20:49 UTC, RaduNichita commented on README.md
> +```console
I think you should say what is the purpose of this command

2023-07-29 20:49 UTC, RaduNichita commented on README.md
> +UK_DEFCONFIG=$(pws)/.config... make defconfig
I think here we should give an example for the .... Otherwise, I would be tempted to run the command like it is.

2023-07-29 20:49 UTC, RaduNichita commented on README.md
>  # Lua on Unikraft
Provide a short description on what is the purpose of the application, similar to [here](https://github.com/unikraft/app-nginx)

2023-07-29 20:49 UTC, RaduNichita commented on README.md
> +kraft build -t lua-fc-arm64-initrd -j $(nproc)
I have one question: is there a particular reason for which the running of the application is done without `kraft run`?

2023-07-30 08:29 UTC, RaduNichita commented
Should we have add a config for `arm64` for Firecracker, @razvand?

2023-07-30 12:15 UTC, StefanJum reviewed
The commands work fine, all good besides the README file that needs updating to match the other applications.

2023-07-30 16:05 UTC, razvand commented
> Should we have add a config for `arm64` for Firecracker, @razvand?

I wasn't able to get that to run, so not yet. But soon.

2023-08-01 09:50 UTC, StefanJum requested changes
Almost there. The last 2 commits show up as `razvand authored and jobpaardekooper committed`, if you took the commits from some other branch or pr please add Job's `signed-off`/`co-authored` tag.

2023-08-01 09:50 UTC, StefanJum commented on README.md
> +UK_DEFCONFIG=$(pwd)/.config.lua0qemu-aarch64-9pfs make defconfig
```suggestion
UK_DEFCONFIG=$(pwd)/.config.lua_qemu-aarch64-9pfs make defconfig
```

2023-08-02 11:20 UTC, RaduNichita requested changes
Looks very good, thanks @razvand. One small comment from me.

2023-08-02 11:20 UTC, RaduNichita commented on README.md
> +Otherwise, we recommend building for `qemu/x86_64` for an `initrd` support filesystem like so:
```suggestion
Otherwise, we recommend building for `qemu/x86_64` with `initrd` support filesystem like so:
```

2023-08-07 05:57 UTC, StefanJum approved these changes
All good on my side, @RaduNichita please review it and I'll add the tag after you're ok

2023-08-07 08:26 UTC, RaduNichita approved these changes
All good now. Many thanks @razvand 

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-07 08:27 UTC, StefanJum approved these changes
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-07 12:43 UTC, StefanJum approved these changes
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-07 12:52 UTC, RaduNichita approved these changes
All good.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-07 14:20 UTC, closed without merging