Change newlib with musl
unikraft/app-lua pull request #9
Opened 2023-07-15 13:03 UTC by JADarius

This PR changes the the newlib dependency with musl.
In theory, this should work, but when I try to run it and give it any lua instructions it crashes.
Any suggestion would be appreciated.

2023-07-15 13:05 UTC, JADarius commented
The error is:
```
Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
           Atlas 0.13.1~e467cdf6-custom
[    0.166974] Info: [libukboot] <boot.c @  369> Pre-init table at 0x2540b0 - 0x2540b0
[    0.172812] Info: [libukboot] <boot.c @  380> Constructor table at 0x2540b0 - 0x2540b0
[    0.178848] Info: [libukboot] <boot.c @  393> Environment variables:
[    0.183509] Info: [libukboot] <boot.c @  395>        PATH=/bin
[    0.188111] Info: [libukboot] <boot.c @  401> Calling main(1, ['build/app-lua_qemu-x86_64'])
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
> ls
[    2.101800] CRIT: [libkvmplat] <traps.c @   84> Unhandled Trap 6 (invalid opcode), error code=0x0
[    2.108398] Info: [libkvmplat] <traps.c @   86> Regs address 0x28ff50
[    2.113015] CRIT: [libkvmplat] <trace.c @   41> RIP: 0000000000000003 CS: 0008
[    2.118252] CRIT: [libkvmplat] <trace.c @   42> RSP: 00000000002b8968 SS: 0010 EFLAGS: 00010283
[    2.124875] CRIT: [libkvmplat] <trace.c @   44> RAX: 0000000000000000 RBX: 0000000000000228 RCX: 0000000000000000
[    2.131821] CRIT: [libkvmplat] <trace.c @   46> RDX: 0000000000000000 RSI: 00000000002b8930 RDI: 0000000000000000
[    2.138914] CRIT: [libkvmplat] <trace.c @   48> RBP: 0000000000000000 R08: 00000000001f4336 R09: 000000007fffffff
[    2.146161] CRIT: [libkvmplat] <trace.c @   50> R10: 0000000000000000 R11: 0000000000000000 R12: 0000000000000000
[    2.152967] CRIT: [libkvmplat] <trace.c @   52> R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
[    2.159765] CRIT: [libkvmplat] <traps.c @   90> Crashing
[    2.164422] Info: [libkvmplat] <shutdown.c @   35> Unikraft halted

```

2023-07-15 13:07 UTC, JADarius commented
From testing with gdb, it seems the issue is related with signals. The function `docall` from lua.c is the function where the error appears (lua.c:161).

2023-07-15 13:41 UTC, eduardvintila requested changes
Great job, @JADarius. You are correct - the runtime error is indeed caused by a `uksignal` issue. There is a [PR](https://github.com/unikraft/unikraft/pull/924/)  already on Unikraft core which fixes the problem.

Please [`sign-off`](https://docs.pi-hole.net/guides/github/how-to-signoff/) your commit and use present tense in the commit title (i.e. `Update newlib references to musl`)

2023-07-15 14:43 UTC, eduardvintila requested changes
Looks great, @JADarius! Just use "Change" (with a capital "C) instead of "change" in the commit name and I'll approve the PR 👍🏻

2023-07-15 15:16 UTC, eduardvintila approved these changes
All good, thank you!

Reviewed-by: Eduard Vintilă <eduard.vintila47@gmail.com>

2023-07-17 08:19 UTC, StefanJum requested changes
Thanks @JADarius. See the comments and please update the commit message, since this pr will do more than cahnge `newlib` to `musl` (it also update the kraft.yaml file and adds the Makefile* files). You can also split the commit into more if you think that's more fit.

2023-07-17 08:19 UTC, StefanJum commented on kraft.yaml
> +    version: '0.13.1'
```suggestion
    version: 'stable'
```

2023-07-17 08:19 UTC, StefanJum commented on kraft.yaml
Please replace `kvm` with `qemu` under `targets`

2023-07-18 16:39 UTC, razvand requested changes
Thanks, @JADarius. I tested and it works.

Please use a prefix such as `Makefile*:` and `kraft.yaml:` for the two commits.

Also add an extensive commit description (separate by a blank line from the commit message). The description should provide the motivation and outcome of the commit changes.

2023-07-25 18:43 UTC, StefanJum approved these changes
All good, thanks.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-07-25 18:44 UTC, razvand approved these changes
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-07-26 07:52 UTC, closed without merging